full_name = "gela gamkrelidze"
print (full_name)
print (len(full_name))
if 15>10:
    print (full_name)
if 119>115:
    print (full_name)
print (full_name[0])
print ("k" in full_name)
print ("0" not in full_name)
print (full_name[2:9])
print (full_name[0:9])
print (full_name[1:9])
print (full_name[:5])
print (full_name[1:9:2])
print (full_name[1:11:3])
print (full_name[1:11:2])
print (full_name[1:11:5])
print (full_name[1:11:3])
print (full_name[-1])
print (full_name[-1:-5])
print (full_name [-1 :-5:-1])
print (full_name[1:5])
print (full_name.upper())
print (full_name.strip())
print (full_name.replace("e", "-" ))